version: "3"

services:
  nginx:
    build: docker/nginx
    ports:
      - "8080:80"

  db:
    build:
      dockerfile: docker/db/Dockerfile
    env_file:
      - .env
    expose:
      - "3306"

  node-service:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    expose:
      - "3000"
    depends_on:
      - db
